from . import test_catalog
from . import test_products_api
from . import test_leads_api
from . import test_portal_api
from . import test_checkout_api
from . import test_registration_api
from . import test_shop_api
from . import test_reviews_api
from . import test_wishlist_api
from . import test_addresses_api
